speed test

In [23]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()

print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2   # Vectorized operation
end = time.time()

print("NumPy array addition time:", end - start)

Python list addition time: 0.05219006538391113
NumPy array addition time: 0.015675067901611328


In [24]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [25]:
# Python list (loop-based)
arr1 =list(range(1, 1000000))
start_time = time.time()
list_squares = [x ** 2 for x in arr1]
end_time = time.time()
print("Python list time:", end_time - start_time)
# NumPy (vectorized)
start_time = time.time()
numpy_squares = np.array(arr1) ** 2
end_time = time.time()
print("NumPy array time:", end_time - start_time)

Python list time: 0.24579644203186035
NumPy array time: 0.04944443702697754


In [26]:
import numpy as np
arr = np.array(range(10, 100))
# print(arr)
print(arr.shape)


(90,)


In [27]:
import numpy as np
import time

size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))
strat = time.time()
start = time.time()
result = [x * y for x, y in zip(list1, list2)]
stop = time.time()
print("The running time of the python script is:" , stop - strat)

arr1 = np.array(list1)
arr2 = np.array(list2)

strat = time.time()
result = arr1  * arr2
stop = time.time()
print("The running time of the np script is:" , stop - strat)



The running time of the python script is: 0.10721468925476074
The running time of the np script is: 0.011005640029907227


In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[4,8,3]])
print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 8 3]]


In [33]:
print("shape: ", myarr.shape)
print("Size: ", myarr.size)
print("Dimentions: ", myarr.ndim)
print("Data Type: ", myarr.dtype)

shape:  (4, 3)
Size:  12
Dimentions:  2
Data Type:  int64


In [ ]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[4,8,3]], dtype = np.float32)
print(myarr.dtype)

float32


In [35]:
myarr.shape

(4, 3)

In [36]:
reshaped = myarr.reshape((3 , 4))
reshaped

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [9., 4., 8., 3.]], dtype=float32)

In [37]:
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [4., 8., 3.]], dtype=float32)

In [39]:
myarr.flatten()

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 4., 8., 3.], dtype=float32)

indexing and slicing

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[4,8,3]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 8, 3]])

In [5]:
flat = arr.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 8, 3])

In [6]:
flat[3]

np.int64(4)

In [7]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 8, 3])

In [9]:
b = flat [3:8]
b

array([4, 5, 6, 7, 8])

In [10]:
b[0] = 786

In [11]:
flat

array([  1,   2,   3, 786,   5,   6,   7,   8,   9,   4,   8,   3])

In [16]:
arr = np.array([1,3,4,5,6,7,7,8,6,4,32,23])
idx = [0,3,10]
(arr[idx])


array([ 1,  5, 32])

In [19]:
arr = np.array([1,3,4,5,6,7,7,8,6,4,32,23])
max = arr > 25
(arr[max])

array([32])

In [25]:
np.full((3,3),99)


array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [32]:
arr = np.array([1.23,2.23,3.23,5.66])
arr_int = arr.astype(int)
print(arr_int.dtype)

int64


In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
idx = [1,3,5,7,9]
print(arr[idx])

[ 2  4  6  8 10]


In [45]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],)
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
mask = arr>=50
print(arr[mask])

[ 50  60  70  80  90 100]


In [52]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(np.sum(arr, axis = 0))

[12 15 18]


In [54]:
print(np.sum(arr, axis = 1))

[ 6 15 24]


In [55]:
print(arr[1,2])

6


In [56]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [57]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])

In [58]:
print(arr3D.shape)

(2, 2, 3)


In [59]:
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [60]:
print(arr3D[0,1,2])

6


In [63]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [76]:
first_col = arr3D[1:,0:,0]
first_col

array([[ 7, 10]])

In [75]:
first_rows = arr3D[:,0,:]
first_rows

array([[1, 2, 3],
       [7, 8, 9]])

In [77]:
arr3D[:,1] = 0
arr3D

array([[[1, 2, 3],
        [0, 0, 0]],

       [[7, 8, 9],
        [0, 0, 0]]])

In [78]:
print(arr.dtype)

int64


In [79]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)

float64


In [80]:
arr_dchange = arr.astype(np.int32)

In [84]:
print(arr_dchange)
print(arr_dchange.dtype)

[1 2 3]
int32


In [87]:
arr_large = np.array([1000000, 2000000, 3000000], dtype = np.int64)
arr_small = arr_large.astype(np.int32)
print(arr_small)
print(arr_small.dtype)
print(arr_large.dtype)

[1000000 2000000 3000000]
int32
int64


In [88]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)
print(arr_int32.nbytes)

24
12


In [89]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [90]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


In [91]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # Vectorized operation
print(result) # Output: [1 4 9 16 25]


[ 1  4  9 16 25]


In [92]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10 # Broadcasting: 10 is added to all elements
print(result) # Output: [11 12 13 14 15]


[11 12 13 14 15]


In [93]:

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
result

array([5, 7, 9])

In [95]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2 # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


In [96]:
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [119]:
arr_mean = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# mean = np.mean(arr_mean)
# mean
print(np.min(arr_mean))
print(np.max(arr_mean))
print(np.std(arr_mean))
print(np.var(arr_mean))
print(np.sum(arr_mean))
print(np.prod(arr_mean))
print(np.median(arr_mean))
print(np.percentile(arr_mean,80))
print(np.argmin(arr_mean))
print(np.argmax(arr_mean))
print(np.corrcoef(arr_mean))
print(np.unique(arr_mean))
print(np.diff(arr_mean))
print(np.cumsum(arr_mean))
print(np.log(arr_mean))
print(np.exp(arr_mean))


10
50
10.801234497346433
116.66666666666667
450
1012934162288508928
30.0
40.0
0
14
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[10 15 20 25 30 35 40 45 50]
[[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]]
[ 10  30  60  75 100 135 155 185 225 250 285 330 360 400 450]
[[2.30258509 2.99573227 3.40119738]
 [2.7080502  3.21887582 3.55534806]
 [2.99573227 3.40119738 3.68887945]
 [3.21887582 3.55534806 3.80666249]
 [3.40119738 3.68887945 3.91202301]]
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [3.26901737e+06 7.20048993e+10 1.58601345e+15]
 [4.85165195e+08 1.06864746e+13 2.35385267e+17]
 [7.20048993e+10 1.58601345e+15 3.49342711e+19]
 [1.06864746e+13 2.35385267e+17 5.18470553e+21]]


In [120]:
import pandas as pd


In [ ]:
s1 = pd.Series([71,24,52,81,91,87,45,67])


In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
print(s1)

0    71
1    24
2    52
3    81
4    91
5    87
6    45
7    67
dtype: int64


In [127]:
s2 = pd.Series([71,24,52,81,91,87,45,67], index = ["harry","Shubh","Ameen","Raj","Milan","Saif","Aakash", "Rani"])
print(s2)

harry     71
Shubh     24
Ameen     52
Raj       81
Milan     91
Saif      87
Aakash    45
Rani      67
dtype: int64


In [128]:
s2["Shubh"]

np.int64(24)

In [132]:
data = {
"name": ["Alice", "Bob", "Charlie"],
"age": [25, 30, 35],
"city": ["Delhi", "Mumbai", "Bangalore"]
}

df = pd.DataFrame(data)
df

,name,age,city
0,Alice,25,Delhi
1,Bob,30,Mumbai
2,Charlie,35,Bangalore


In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [134]:
df.columns

Index(['name', 'age', 'city'], dtype='object')